In [ ]:
import numpy as np
np.set_printoptions(precision=3)


In [2]:
import tensorflow as tf
tf.__version__

'2.17.0'

In [ ]:
a = np.array([1, 2, 3], dtype=np.int32)
b = [4, 5, 6]
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)
print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [ ]:
t_one = tf.ones((2, 3))
t_one.shape
print(t_one)


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [ ]:
t_one.numpy() # convert to array

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
print(const_tensor)

tf.Tensor([1.2   5.    3.142], shape=(3,), dtype=float32)


In [ ]:
# tf.fill
tf.fill((2, 3), 10) # => gen value to tensor


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [10, 10, 10]], dtype=int32)>

In [ ]:
# tensorflow one-hot func
tf.one_hot([0, 1, 2, 3, 5, 6], 4)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# change the shape of data to number or string or something >?
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new)
print(t_a_new.shape)

t_test = tf.cast([10, 20, True], tf.int32)
print(t_test)
print(t_test.shape)



tf.Tensor([1 2 3], shape=(3,), dtype=int64)
(3,)
tf.Tensor([10 20  1], shape=(3,), dtype=int32)
(3,)


In [ ]:
t = tf.random.uniform(shape=(3, 5))
print(t)

t_tr = tf.transpose(t)
print(t_tr)

print(t.shape, '--> ', t_tr.shape)

tf.Tensor(
[[0.673 0.84  0.207 0.237 0.976]
 [0.523 0.948 0.032 0.083 0.595]
 [0.156 0.764 0.027 0.966 0.113]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[0.673 0.523 0.156]
 [0.84  0.948 0.764]
 [0.207 0.032 0.027]
 [0.237 0.083 0.966]
 [0.976 0.595 0.113]], shape=(5, 3), dtype=float32)
(3, 5) -->  (5, 3)


In [ ]:
t = tf.random.uniform((30,), dtype=tf.float32)  # Generates a tensor of shape (30,) with random values
print(t)
# Reshape the tensor to shape (5, 6)
t_reshape = tf.reshape(t, shape=(5, 6))

print(t_reshape)

tf.Tensor(
[0.665 0.235 0.6   0.171 0.642 0.817 0.819 0.748 0.524 0.374 0.225 0.43
 0.498 0.217 0.215 0.89  0.907 0.467 0.481 0.712 0.339 0.388 0.436 0.383
 0.52  0.008 0.247 0.06  0.328 0.655], shape=(30,), dtype=float32)
tf.Tensor(
[[0.665 0.235 0.6   0.171 0.642 0.817]
 [0.819 0.748 0.524 0.374 0.225 0.43 ]
 [0.498 0.217 0.215 0.89  0.907 0.467]
 [0.481 0.712 0.339 0.388 0.436 0.383]
 [0.52  0.008 0.247 0.06  0.328 0.655]], shape=(5, 6), dtype=float32)


In [ ]:
t = tf.zeros((1, 2, 1, 4, 1))
t_sqz = tf.squeeze(t, axis=(2, 4))

print(t.shape, ' --> ', t_sqz.shape)

(1, 2, 1, 4, 1)  -->  (1, 2, 4)


In [ ]:
# operation with tensor
tf.random.set_seed(1)

t1 = tf.random.uniform(shape=(5, 2), minval = -1.0, maxval = 1.0)
t2 = tf.random.normal(shape=(5, 2), mean = 0.0, stddev=1.0) # stddev => standart deviation

print(t1)
print(t2)

tf.Tensor(
[[-0.67   0.803]
 [ 0.262 -0.131]
 [-0.416  0.285]
 [ 0.952 -0.13 ]
 [ 0.32   0.21 ]], shape=(5, 2), dtype=float32)
tf.Tensor(
[[ 0.403 -1.088]
 [-0.063  1.337]
 [ 0.712 -0.489]
 [-0.764 -1.037]
 [-1.252  0.021]], shape=(5, 2), dtype=float32)


In [ ]:
t3 = tf.multiply(t1, t2).numpy() # => Multiple t3[i] = t1[i]*t2[i]
print(t3)

[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


In [ ]:
t4 = tf.math.reduce_mean(t1, axis=0)
print(t4)

tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)


In [ ]:
t5 = tf.linalg.matmul(t1, t2, transpose_b = True)
# the matrix b will transpose befor call the func to mul two matrix
print(t5)

t6 = tf.linalg.matmul(t1, t2, transpose_a = True)
print(t6)


tf.Tensor(
[[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[-1.711  0.302]
 [ 0.371 -1.049]], shape=(2, 2), dtype=float32)


In [ ]:
# nomal distrivusion
norm_t1 = tf.norm(t1, ord=2, axis=1).numpy()
print(norm_t1)

# return the distance euclid: in axis = 1 -> row[i] = sqrt(for i, sum = 0, in range(num_of_column): sum += i^2 => return sum)
# ord = 2 => euclid




[1.046 0.293 0.504 0.96  0.383]


In [ ]:
np.sqrt(np.sum(np.square(t1), axis=1))


array([1.046, 0.293, 0.504, 0.96 , 0.383], dtype=float32)

In [ ]:
tf.random.set_seed(1)
t = tf.random.uniform((6, ))

print(t.numpy())

t_splits = tf.split(t, 3)

[item.numpy() for item in t_splits]

[0.165 0.901 0.631 0.435 0.292 0.643]


[array([0.165, 0.901], dtype=float32),
 array([0.631, 0.435], dtype=float32),
 array([0.292, 0.643], dtype=float32)]

In [ ]:
# split(), stack(), concatenate()


In [ ]:
A = tf.ones((3, ))
B = tf.zeros((3, ))

C = tf.concat([A, B], axis=0)
print(C.numpy())



[1. 1. 1. 0. 0. 0.]


In [ ]:
C_stack = tf.stack([A, B], axis =1)
print(C_stack)

tf.Tensor(
[[1. 0.]
 [1. 0.]
 [1. 0.]], shape=(3, 2), dtype=float32)


In [6]:
a = [1.2, 3.4, 7.5, 4.1, 1, 2, 4, 5]
ds = tf.data.Dataset.from_tensor_slices(a)
print(ds)

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.float32, name=None)>


In [4]:
for item in ds:
  print(item)

tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(3.4, shape=(), dtype=float32)
tf.Tensor(7.5, shape=(), dtype=float32)
tf.Tensor(4.1, shape=(), dtype=float32)


In [7]:
ds_batch = ds.batch(3)
for i, elem in enumerate(ds_batch, 100):
  print('batch {}:'.format(i), elem.numpy())

  # batch element to each batch has n element = 3.

batch 100: [1.2 3.4 7.5]
batch 101: [4.1 1.  2. ]
batch 102: [4. 5.]


In [9]:
tf.random.set_seed(1)

t_x = tf.random.uniform([4, 3], dtype=tf.float32)
t_y = tf.range(4)

ds_x = tf.data.Dataset.from_tensor_slices(t_x)
ds_y = tf.data.Dataset.from_tensor_slices(t_y)

ds_joint = tf.data.Dataset.zip((ds_x, ds_y))
for example in ds_joint:
  print('  x: ', example[0].numpy())
  print('  y: ', example[1].numpy())

  x:  [0.16513085 0.9014813  0.6309742 ]
  y:  0
  x:  [0.4345461  0.29193902 0.64250207]
  y:  1
  x:  [0.9757855  0.43509948 0.6601019 ]
  y:  2
  x:  [0.60489583 0.6366315  0.6144488 ]
  y:  3


In [10]:
ds_trans = ds_joint.map(lambda x, y: (x*2-1.0, y))

for example in ds_trans:
  print('  x: ', example[0].numpy())
  print('  y: ', example[1].numpy())


  x:  [-0.6697383   0.80296254  0.26194835]
  y:  0
  x:  [-0.13090777 -0.41612196  0.28500414]
  y:  1
  x:  [ 0.951571   -0.12980103  0.32020378]
  y:  2
  x:  [0.20979166 0.27326298 0.22889757]
  y:  3


In [12]:
ds = ds_joint.shuffle(buffer_size = len(t_x))

for example in ds:
  print('  x: ', example[0].numpy())
  print('  y: ', example[1].numpy())

# => shuffle data


  x:  [0.4345461  0.29193902 0.64250207]
  y:  1
  x:  [0.9757855  0.43509948 0.6601019 ]
  y:  2
  x:  [0.60489583 0.6366315  0.6144488 ]
  y:  3
  x:  [0.16513085 0.9014813  0.6309742 ]
  y:  0


In [15]:
ds = ds_joint.batch(batch_size=3, drop_remainder=False)

batch_x, batch_y = next(iter(ds))
print(batch_x.numpy())
print(batch_y.numpy())


# shuffle(), batch(), repeat()


[[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]]
[0 1 2]


In [19]:
# read data from disk internal
import pathlib
imgdir_path = pathlib.Path('cat_and_dog')

file_list = sorted([str(path) for path in imgdir_path.glob('*.jpg')])

print(file_list)

cat_and_dog
[]


In [21]:
import drive
file_list = sorted([f for f in os.listdir(imgdir_path) if f.endswith('.jpg') or f.endswith('.JPG')])
print(file_list)

ModuleNotFoundError: No module named 'drive'

In [26]:
from google.colab import drive
drive.mount('/content/drive')



Mounted at /content/drive


In [41]:
from google.colab import drive

from PIL import Image
import os



In [43]:
# Specify the directory containing images
image_dir = '/content/drive/MyDrive/Colab Notebooks/cat_and_dog'

# Iterate through files in the directory
for filename in os.listdir(image_dir):
  if filename.endswith(('.jpg', '.JPG', '.png', '.jpeg')):  # Check for common image extensions
    # Construct full file path
    filepath = os.path.join(image_dir, filename)
    print(filepath)
    # Open and display the image
    with Image.open(filepath) as img:
      img.show()

/content/drive/MyDrive/Colab Notebooks/cat_and_dog/cat.9980.jpg
/content/drive/MyDrive/Colab Notebooks/cat_and_dog/cat.9984.jpg
/content/drive/MyDrive/Colab Notebooks/cat_and_dog/cat.9982.jpg
/content/drive/MyDrive/Colab Notebooks/cat_and_dog/cat.9979.jpg
/content/drive/MyDrive/Colab Notebooks/cat_and_dog/dog.9960.jpg
/content/drive/MyDrive/Colab Notebooks/cat_and_dog/dog.9935.jpg
/content/drive/MyDrive/Colab Notebooks/cat_and_dog/dog.9967.jpg
/content/drive/MyDrive/Colab Notebooks/cat_and_dog/dog.996.jpg


In [45]:
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(10, 10))
for i, file in enumerate(file_list):
  img_raw = tf.i0.read_file(file)
  img = tf.image.decode_jpeg(img_raw)
  print("Image shape:", img.shape)
  ax = fig.add_subplot(2, 3, i+1)
  ax.set_xticks([])
  ax.set_yticks([])
  ax.imshow(img)
  ax.set_title(os.path.basename(file), size=15)
plt.tight_layout()
plt.show()

<Figure size 1000x1000 with 0 Axes>